{{- if .Values.runtime.kubernetes.namespace }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ciab-agent
  namespace: {{ .Values.runtime.kubernetes.namespace }}
  labels:
    {{- include "ciab.labels" . | nindent 4 }}
    ciab/managed-by: ciab
{{- end }}
